import { pair } from "./content";
import { validateLadderContent, type LadderContent } from "./content-schema";

const common = {
  questionFormat: "original-four" as const,
  mechanicsVersion: "chapter-route.v1" as const,
};

export const threePapersOriginal = validateLadderContent({
  ...common,
  activityId: "three-papers-one-thread",
  slug: "three-papers-one-thread",
  title: pair("Three papers, one thread", "Tiga makalah, satu benang merah"),
  version: "three-papers-original.2026-10-09.v1",
  durationMs: 97115,
  audioHash: "d728ede236948a4877dc38926114abdad19ff358dc35414f9be107ffbeed42c2",
  items: [
    {
      id: "weekly-work",
      title: pair("A demanding week", "Minggu yang sibuk"),
      startMs: 8250,
      endMs: 30000,
      prompt: pair("What has the man been busy doing all week?", "Apa yang menyibukkan pembicara laki-laki sepanjang minggu?"),
      options: [
        pair("Writing papers for his classes.", "Menulis makalah untuk kelas-kelasnya."),
        pair("Meeting with his professors.", "Bertemu dengan para dosennya."),
        pair("Doing extra work in the chemistry lab.", "Mengerjakan tugas tambahan di laboratorium kimia."),
        pair("Working overtime as a librarian.", "Bekerja lembur sebagai pustakawan."),
      ],
      first: 0,
      repairKey: 2,
      repair: {
        prompt: pair("Which detail best explains why the work fills his week?", "Detail mana yang paling menjelaskan mengapa tugas itu memenuhi minggunya?"),
        options: [
          pair("One shared assignment needs a final edit.", "Satu tugas bersama perlu penyuntingan akhir."),
          pair("A laboratory shift takes place every evening.", "Giliran laboratorium berlangsung setiap malam."),
          pair("Three separate class papers need attention.", "Tiga makalah kelas yang terpisah perlu dikerjakan."),
        ],
        focus: pair("Listen for the correction after the woman says 'a paper.'", "Dengarkan koreksi setelah pembicara perempuan menyebut 'sebuah makalah'."),
        hint: pair("Notice the number of assignments and the subjects he names.", "Perhatikan jumlah tugas dan mata kuliah yang ia sebutkan."),
        supportedMeaning: pair("He is occupied with three separate papers for different classes.", "Ia sibuk dengan tiga makalah terpisah untuk mata kuliah yang berbeda."),
      },
      transcript: "The opening exchange establishes that the man has spent the week working on three separate class papers.",
      reasons: ["The man identifies several class papers.", "Professor meetings are not his stated work.", "Chemistry belongs to the later joke.", "The library is a location, not his job."],
    },
    {
      id: "research-plan",
      title: pair("A more connected plan", "Rencana yang lebih terhubung"),
      startMs: 24500,
      endMs: 72000,
      prompt: pair("What does the woman suggest the man do to make his work easier?", "Apa saran pembicara perempuan agar tugas pembicara laki-laki lebih mudah?"),
      options: [
        pair("Spend more time in the library.", "Menghabiskan lebih banyak waktu di perpustakaan."),
        pair("Write just one paper for all his classes.", "Menulis hanya satu makalah untuk semua kelasnya."),
        pair("Drop one of his courses.", "Berhenti mengikuti salah satu mata kuliahnya."),
        pair("Do his research on closely related topics.", "Melakukan riset tentang topik-topik yang saling berkaitan."),
      ],
      first: 3,
      repairKey: 1,
      repair: {
        prompt: pair("What is shared across her plan, and what remains separate?", "Apa yang sama dalam rencananya, dan apa yang tetap terpisah?"),
        options: [
          pair("One paper is submitted to every class.", "Satu makalah diserahkan ke semua kelas."),
          pair("The research topics connect, while the papers keep different angles.", "Topik risetnya saling terhubung, sementara makalahnya memakai sudut berbeda."),
          pair("Each paper moves to a different historical period.", "Setiap makalah beralih ke periode sejarah yang berbeda."),
        ],
        focus: pair("Listen from the rejected one-paper idea through the three subject examples.", "Dengarkan dari ide satu makalah yang ditolak hingga tiga contoh mata kuliah."),
        hint: pair("Separate one shared theme from one shared submission.", "Bedakan satu tema bersama dari satu makalah yang sama."),
        supportedMeaning: pair("She recommends related research topics with a distinct focus for each paper.", "Ia menyarankan topik riset yang berkaitan dengan fokus berbeda untuk tiap makalah."),
      },
      transcript: "The woman turns the rejected single-paper idea into separate papers connected by one broad theme and distinct disciplinary angles.",
      reasons: ["More library time does not reorganize the work.", "The professors reject a single shared submission.", "Dropping a course is not proposed.", "Connected research topics describe her plan."],
    },
    {
      id: "theme-example",
      title: pair("The example theme", "Contoh tema"),
      startMs: 43000,
      endMs: 78500,
      prompt: pair("Why does the woman mention Romanticism?", "Mengapa pembicara perempuan menyebut Romantisisme?"),
      options: [
        pair("She once wrote about it.", "Ia pernah menulis tentangnya."),
        pair("She thinks the man should write about it.", "Ia berpikir pembicara laki-laki sebaiknya menulis tentangnya."),
        pair("She has been studying it recently.", "Ia baru-baru ini mempelajarinya."),
        pair("She particularly likes Romantic poetry.", "Ia sangat menyukai puisi Romantik."),
      ],
      first: 1,
      repairKey: 0,
      repair: {
        prompt: pair("What role does Romanticism play in her suggestion?", "Apa peran Romantisisme dalam sarannya?"),
        options: [
          pair("It is an example theme he could use across the papers.", "Itu adalah contoh tema yang dapat ia gunakan di seluruh makalah."),
          pair("It is a course she wants him to drop.", "Itu adalah mata kuliah yang ia ingin ia tinggalkan."),
          pair("It is a poem she asks him to summarize for her.", "Itu adalah puisi yang ia minta untuk diringkas."),
        ],
        focus: pair("Listen to the three ways she connects the theme to his subjects.", "Dengarkan tiga cara ia menghubungkan tema itu dengan mata kuliahnya."),
        hint: pair("Ask whether she is describing her own work or proposing his next direction.", "Tanyakan apakah ia membahas pekerjaannya sendiri atau mengusulkan arah untuk tugas pembicara laki-laki."),
        supportedMeaning: pair("She offers Romanticism as a possible shared theme for his three papers.", "Ia menawarkan Romantisisme sebagai kemungkinan tema bersama untuk tiga makalahnya."),
      },
      transcript: "The woman proposes Romanticism and illustrates how the man could approach it through three different subjects.",
      reasons: ["She does not refer to her own former paper.", "She proposes it as his organizing theme.", "Recent personal study is not stated.", "Personal preference is not her reason."],
    },
    {
      id: "closing-offer",
      title: pair("The closing exchange", "Percakapan penutup"),
      startMs: 73500,
      endMs: 97115,
      prompt: pair("Why doesn't the woman want any help from the man?", "Mengapa pembicara perempuan tidak menginginkan bantuan dari pembicara laki-laki?"),
      options: [
        pair("She knows he is very busy.", "Ia tahu pembicara laki-laki sangat sibuk."),
        pair("He has already helped her enough.", "Pembicara laki-laki sudah cukup banyak membantunya."),
        pair("He doesn't know enough chemistry.", "Pembicara laki-laki tidak cukup memahami kimia."),
        pair("She doesn't need any help.", "Ia tidak membutuhkan bantuan apa pun."),
      ],
      first: 2,
      repairKey: 1,
      repair: {
        prompt: pair("Why is his specific offer not useful to her?", "Mengapa tawaran khususnya tidak berguna baginya?"),
        options: [
          pair("He has no experience with the subject of her report.", "Ia tidak berpengalaman dalam bidang laporan pembicara perempuan."),
          pair("She has already submitted the report.", "Ia sudah menyerahkan laporan itu."),
          pair("The report belongs to one of his own classes.", "Laporan itu untuk salah satu kelas pembicara laki-laki."),
        ],
        focus: pair("Listen to his response when she names the chemistry report.", "Dengarkan tanggapannya saat pembicara perempuan menyebut laporan kimia."),
        hint: pair("The reason follows his offer and concerns what he has never studied.", "Alasannya muncul setelah tawarannya dan berkaitan dengan bidang yang belum pernah ia pelajari."),
        supportedMeaning: pair("His offer cannot help because he has never taken chemistry.", "Tawarannya tidak dapat membantu karena ia belum pernah mengambil mata kuliah kimia."),
      },
      transcript: "When she jokingly names a chemistry lab report, he admits that he has never taken chemistry, so that offer is not useful.",
      reasons: ["His workload is visible but not her stated reason.", "No earlier help is mentioned.", "His lack of chemistry background blocks the offer.", "She names a report she could use help with."],
    },
  ],
} satisfies LadderContent);

export const oceanCurrentsOriginal = validateLadderContent({
  ...common,
  activityId: "ocean-currents-in-motion",
  slug: "ocean-currents-in-motion",
  title: pair("Ocean currents in motion", "Arus laut yang bergerak"),
  version: "ocean-currents-original.2026-10-09.v1",
  durationMs: 99036,
  audioHash: "23d072cf57c1db8668299d349f87916584025b578942b98aed8d4326fc9580fa",
  items: [
    {
      id: "main-topic", title: pair("The conversation's focus", "Fokus percakapan"), startMs: 0, endMs: 99036,
      prompt: pair("What are the speakers mainly discussing?", "Apa yang terutama dibahas oleh kedua pembicara?"),
      options: [pair("Collecting objects on the beach.", "Mengumpulkan benda di pantai."), pair("Creating computer models.", "Membuat model komputer."), pair("Mapping currents in the ocean.", "Memetakan arus di laut."), pair("Tracking water pollution.", "Melacak pencemaran air.")],
      first: 2, repairKey: 1,
      repair: { prompt: pair("What connects the bottles, computer model, and sneakers?", "Apa yang menghubungkan botol, model komputer, dan sepatu?"), options: [pair("They are examples of beach art.", "Semuanya contoh seni pantai."), pair("They help explain how ocean currents are traced and tested.", "Semuanya membantu menjelaskan cara arus laut dilacak dan diuji."), pair("They identify sources of water pollution.", "Semuanya mengidentifikasi sumber pencemaran air.")], focus: pair("Replay the whole conversation and track the repeated idea linking each example.", "Putar ulang seluruh percakapan dan ikuti gagasan berulang yang menghubungkan setiap contoh."), hint: pair("Notice what the scientists wanted to map and what the later event tested.", "Perhatikan apa yang ingin dipetakan para ilmuwan dan apa yang diuji oleh peristiwa berikutnya."), supportedMeaning: pair("The examples build an explanation of mapping and testing ocean-current paths.", "Contoh-contohnya membangun penjelasan tentang pemetaan dan pengujian jalur arus laut.") },
      transcript: "A beach discovery leads to a discussion of ocean currents, bottle releases, a computer model, and an accidental sneaker test.",
      reasons: ["Beach collecting only opens the conversation.", "The model is one method, not the overall topic.", "The discussion centers on mapping ocean currents.", "Pollution tracking is not developed."],
    },
    {
      id: "beach-find", title: pair("The beach discovery", "Temuan di pantai"), startMs: 0, endMs: 18000,
      prompt: pair("What did the man find on the beach?", "Apa yang ditemukan pembicara laki-laki di pantai?"),
      options: [pair("An interesting piece of wood.", "Sepotong kayu yang menarik."), pair("An old shoe.", "Sepatu tua."), pair("A message inside a bottle.", "Pesan di dalam botol."), pair("An unusual shell.", "Cangkang yang tidak biasa.")],
      first: 0, repairKey: 2,
      repair: { prompt: pair("Which object begins the discussion before bottles and shoes are mentioned?", "Benda mana yang memulai pembahasan sebelum botol dan sepatu disebutkan?"), options: [pair("A discarded shoe.", "Sepatu yang terbuang."), pair("A sealed bottle.", "Botol tertutup."), pair("A smooth piece of driftwood.", "Sepotong kayu apung yang halus.")], focus: pair("Listen to the first exchange and the woman's identification of the object.", "Dengarkan percakapan awal dan cara pembicara perempuan mengenali benda itu."), hint: pair("Separate the object in his hand from later hypothetical and reported objects.", "Bedakan benda di tangannya dari benda hipotetis dan benda yang diceritakan kemudian."), supportedMeaning: pair("He begins by showing her an interesting piece of driftwood.", "Ia memulai dengan menunjukkan sepotong kayu apung yang menarik.") },
      transcript: "The man shows the woman a smooth piece of driftwood he has just found in the sand.",
      reasons: ["The found object is driftwood.", "Shoes appear later in the magazine story.", "A bottle is proposed as a method, not found.", "No shell is found."],
    },
    {
      id: "scientist-method", title: pair("The planned method", "Metode yang direncanakan"), startMs: 30000, endMs: 62000,
      prompt: pair("According to the magazine article, what did scientists put into the ocean?", "Menurut artikel majalah itu, apa yang dimasukkan para ilmuwan ke laut?"),
      options: [pair("Chemicals.", "Bahan kimia."), pair("Bottles.", "Botol."), pair("Athletic shoes.", "Sepatu olahraga."), pair("Model boats.", "Kapal model.")],
      first: 1, repairKey: 0,
      repair: { prompt: pair("Which objects were deliberately released to trace where currents carried them?", "Benda mana yang sengaja dilepaskan untuk melacak ke mana arus membawanya?"), options: [pair("Large numbers of bottles.", "Botol dalam jumlah besar."), pair("Pairs of factory sneakers.", "Pasangan sepatu dari pabrik."), pair("Small computer-guided boats.", "Kapal kecil berpemandu komputer.")], focus: pair("Listen from the man's joke about a message through the magazine example.", "Dengarkan dari candaan tentang pesan hingga contoh dalam majalah."), hint: pair("Distinguish the planned release from the later shipping accident.", "Bedakan pelepasan yang direncanakan dari kecelakaan pengiriman kemudian."), supportedMeaning: pair("Scientists deliberately released many bottles and recorded where currents carried them.", "Para ilmuwan sengaja melepaskan banyak botol dan mencatat ke mana arus membawanya.") },
      transcript: "The woman describes oceanographers deliberately releasing many bottles so their destinations could reveal current paths.",
      reasons: ["No chemical release is described.", "Bottles were deliberately released.", "The shoes entered the ocean accidentally.", "No model boats are mentioned."],
    },
    {
      id: "unplanned-test", title: pair("An unexpected experiment", "Eksperimen tak terduga"), startMs: 54000, endMs: 99036,
      prompt: pair("What can be inferred from the story about the sneakers?", "Apa yang dapat disimpulkan dari cerita tentang sepatu olahraga itu?"),
      options: [pair("A storm can change the direction of an ocean current.", "Badai dapat mengubah arah arus laut."), pair("Common items can be works of art.", "Benda sehari-hari dapat menjadi karya seni."), pair("Not all useful experiments are planned ahead of time.", "Tidak semua eksperimen yang berguna direncanakan sebelumnya."), pair("Computers cannot always predict the effects of pollution.", "Komputer tidak selalu dapat memprediksi dampak pencemaran.")],
      first: 2, repairKey: 1,
      repair: { prompt: pair("How did the sneaker event become useful to the scientists?", "Bagaimana peristiwa sepatu itu menjadi berguna bagi para ilmuwan?"), options: [pair("Scientists arranged the storm to redirect the current.", "Ilmuwan mengatur badai untuk mengalihkan arus."), pair("An accidental spill provided an unplanned check of the model.", "Tumpahan tak disengaja memberi pengujian model yang tidak direncanakan."), pair("Artists collected the shoes and documented their shapes.", "Seniman mengumpulkan sepatu dan mendokumentasikan bentuknya.")], focus: pair("Listen for why the shoes entered the water and what their later locations showed.", "Dengarkan mengapa sepatu masuk ke air dan apa yang ditunjukkan lokasi penemuannya kemudian."), hint: pair("Compare the cause of the spill with the scientific value of the result.", "Bandingkan penyebab tumpahan dengan nilai ilmiah hasilnya."), supportedMeaning: pair("The accidental sneaker spill became a useful unplanned test of the current model.", "Tumpahan sepatu yang tidak disengaja menjadi pengujian tak terencana yang berguna bagi model arus.") },
      transcript: "A storm accidentally dumps sneakers from a freighter; where they later wash ashore agrees with the model's prediction.",
      reasons: ["The story does not say the storm redirected the current.", "Art is associated with the opening driftwood, not the inference.", "An accident supplied a useful test that was not planned.", "The prediction succeeded and pollution is not the point."],
    },
  ],
} satisfies LadderContent);
